apiVersion: v1
kind: Service
metadata:
  name: product-service-v1-svc
  labels:
    app: product-service
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 31000
    protocol: TCP
  selector:
    app: product-service